# 1. What is NumPy?

## Concept Explanation

NumPy stands for Numerical Python. It is a Python library mainly used for working with numbers, arrays, and mathematical calculations.

The main feature of NumPy is the `ndarray`, which allows us to store multiple values together and perform calculations on them easily.

Instead of handling each number separately, NumPy allows us to work with many values at the same time. This makes it very useful when working with data.

## Real-world Example

Suppose we have the temperatures recorded for seven days:

28, 30, 29, 31, 32, 30, 27

We can store these values in a NumPy array and quickly find the average, highest temperature, lowest temperature, and other useful information.

## Business Example

A company may have sales values for different months. NumPy can be used to store the sales data and perform calculations such as total sales, average sales, and monthly comparisons.

## AI/ML Example

In AI and Machine Learning, data is mostly represented using numerical values. NumPy arrays are commonly used to store and process these values before they are given to a Machine Learning model.

For example, customer age, income, or other numerical features can be stored and processed using NumPy arrays.

## Python Implementation

In the code below, I create a simple NumPy array and perform a few basic calculations on it.

## Output Explanation

The output shows the values stored in the NumPy array along with the average, maximum, and minimum values.

This shows how NumPy can perform calculations on a group of numbers without handling each value separately.

## Best Practices

- Use NumPy arrays when working with numerical data.
- Use meaningful variable names.
- Check the data before performing calculations.
- Prefer NumPy operations instead of unnecessary loops when working with arrays.

## Common Mistakes

- Forgetting to import NumPy before using it.
- Confusing a NumPy array with a normal Python list.
- Using incorrect data types for numerical calculations.

## Advantages

- Easy to perform numerical calculations.
- Efficient for handling large amounts of numerical data.
- Supports multi-dimensional arrays.
- Provides many useful mathematical functions.
- Works well with Pandas and Machine Learning libraries.

## Limitations

- NumPy is mainly focused on numerical data.
- It does not provide all the features needed for working with labelled or tabular data.
- Beginners may need some practice to understand arrays and their dimensions.

In [1]:
import numpy as np

# Creating a NumPy array with weekly temperature values
temperatures = np.array([28, 30, 29, 31, 32, 30, 27])

print("Temperatures:", temperatures)

# Finding some basic information from the data
print("Average temperature:", np.mean(temperatures))
print("Highest temperature:", np.max(temperatures))
print("Lowest temperature:", np.min(temperatures))

Temperatures: [28 30 29 31 32 30 27]
Average temperature: 29.571428571428573
Highest temperature: 32
Lowest temperature: 27


# 2. Why NumPy?

## Concept Explanation

NumPy is useful because it makes working with numerical data easier and faster.

With normal Python lists, we often need to write loops to perform calculations on every value. NumPy allows us to perform many operations directly on the complete array.

It also provides useful functions for mathematical calculations, statistics, array manipulation, and working with multi-dimensional data.

Because of this, NumPy is commonly used as a basic library in Data Science and Machine Learning.

## Real-world Example

Suppose we have the prices of several products:

100, 150, 200, 250

If we want to increase every price by 10, NumPy can apply the calculation to the whole array at once instead of changing every value separately.

## Business Example

A company may have sales data for many products or months. Using NumPy, the company can quickly calculate totals, averages, differences, and other numerical values.

This becomes especially useful when the dataset contains thousands or millions of values.

## AI/ML Example

In Machine Learning, we usually work with many numerical features.

For example, a dataset may contain:

- Age
- Salary
- Experience
- Purchase amount

NumPy can help store and process these numerical values efficiently before they are used for Machine Learning.

## Python Implementation

In the code below, I compare a simple calculation using a Python list with the same type of calculation using a NumPy array.

The NumPy approach allows the operation to be applied directly to all the values.

## Output Explanation

The output shows that NumPy can apply the same calculation to every value in the array without writing a separate loop.

This is one of the main reasons NumPy is useful when working with numerical data.

## Best Practices

- Use NumPy for numerical and array-based calculations.
- Use vectorized operations whenever possible.
- Keep the data type and array shape in mind.
- Use NumPy functions instead of writing unnecessary loops.

## Common Mistakes

- Thinking NumPy is only useful for Machine Learning.
- Using Python loops when a simple NumPy operation can do the same work.
- Ignoring the shape of arrays when performing operations.

## Advantages

- Makes numerical calculations easier.
- Provides efficient array operations.
- Supports large numerical datasets.
- Provides many mathematical and statistical functions.
- Works well with other Python Data Science libraries.

## Limitations

- NumPy is mainly focused on numerical data.
- It is not designed to replace Pandas for labelled tabular data.
- Understanding array shapes can take some practice.

In [2]:
import numpy as np

# Product prices
prices = np.array([100, 150, 200, 250])

print("Original prices:", prices)

# Increase every price by 10
updated_prices = prices + 10

print("Updated prices:", updated_prices)

# Some basic calculations
print("Total price:", np.sum(prices))
print("Average price:", np.mean(prices))

Original prices: [100 150 200 250]
Updated prices: [110 160 210 260]
Total price: 700
Average price: 175.0


# 3. NumPy Arrays (`ndarray`)

## Concept Explanation

The main data structure in NumPy is called an `ndarray`, which means N-dimensional array.

An ndarray is used to store multiple values together. Unlike a normal Python list, a NumPy array is designed mainly for numerical calculations and can handle data in one or more dimensions.

For example, a 1D array can store a list of marks, while a 2D array can represent rows and columns of data.

## Real-world Example

Suppose we have the marks of five students:

75, 82, 68, 90, 85

We can store these marks in a NumPy array and easily calculate the average or compare the values.

## Business Example

A company may store the monthly sales of different products in a 2D NumPy array.

Rows can represent products and columns can represent different months. This makes it easier to perform calculations on the sales data.

## AI/ML Example

In Machine Learning, datasets are often represented as arrays of numbers.

For example, if we have information about customers such as age, income, and spending score, these values can be arranged in a NumPy array and used during data preprocessing and model development.

## Python Implementation

In the code below, I create both a one-dimensional and a two-dimensional NumPy array.

The example also shows how we can access values from the arrays.

## Output Explanation

The first output shows a simple 1D array containing student marks.

The second output shows a 2D array arranged in rows and columns.

The indexing examples show how individual values can be accessed from both types of arrays.

## Best Practices

- Use NumPy arrays when working mainly with numerical data.
- Keep the structure of the array consistent.
- Check the array shape before performing calculations.
- Use meaningful variable names.

## Common Mistakes

- Confusing a NumPy array with a Python list.
- Using incorrect row or column indexes.
- Assuming every NumPy array has only one dimension.
- Ignoring the shape of a 2D or higher-dimensional array.

## Advantages

- Efficient for numerical calculations.
- Supports one-dimensional and multi-dimensional data.
- Provides convenient indexing and slicing.
- Works well with other Data Science and Machine Learning libraries.

## Limitations

- Mainly designed for numerical data.
- Arrays generally work best when the values have a compatible data type.
- More complex tabular data is often easier to handle with Pandas.

In [3]:
import numpy as np

# Creating a 1D NumPy array
marks = np.array([75, 82, 68, 90, 85])

print("Student marks:")
print(marks)

# Accessing the first mark
print("\nFirst student's mark:", marks[0])

# Creating a 2D NumPy array
sales = np.array([
    [1200, 1500, 1800],
    [1000, 1300, 1600],
    [1400, 1700, 2000]
])

print("\nSales data:")
print(sales)

# Accessing a value from the 2D array
# Row 0, column 1 means first row and second column
print("\nValue from first row, second column:", sales[0, 1])

Student marks:
[75 82 68 90 85]

First student's mark: 75

Sales data:
[[1200 1500 1800]
 [1000 1300 1600]
 [1400 1700 2000]]

Value from first row, second column: 1500


# 4. Creating Arrays

## Concept Explanation

NumPy provides different ways to create arrays depending on what kind of data we need.

The most common way is to use `np.array()` with a Python list or tuple.

NumPy also provides functions such as `np.zeros()`, `np.ones()`, and `np.arange()` when we need arrays with a particular pattern of values.

These functions are useful because we don't always have to enter every value manually.

## Real-world Example

Suppose we want to create a list of daily sales values for a week. We can directly create a NumPy array from the sales numbers.

If we need an array where all values start as zero, such as an empty record for future calculations, `np.zeros()` can be useful.

## Business Example

A company may create an array of zeros for storing initial sales, inventory counts, or other values before actual data is added.

For example, if we want to keep space for the sales of five products, we can start with an array containing five zeros.

## AI/ML Example

In Machine Learning, arrays are often created during data preprocessing.

For example, we may create an array of zeros to initialize values or use `np.arange()` to generate a sequence of numbers for testing and analysis.

## Python Implementation

In the code below, I create arrays using `np.array()`, `np.zeros()`, `np.ones()`, and `np.arange()`.

## Output Explanation

The output shows that each function creates an array in a different way.

`np.array()` creates an array from the values we provide.

`np.zeros()` creates an array filled with zeros.

`np.ones()` creates an array filled with ones.

`np.arange()` creates a sequence of numbers within the given range.

## Best Practices

- Use `np.array()` when you already have values to convert into an array.
- Use `np.zeros()` and `np.ones()` when you need an array with an initial value.
- Check the number of elements before using the array in further calculations.
- Use `np.arange()` carefully when defining the start and stop values.

## Common Mistakes

- Forgetting that the stop value in `np.arange()` is not included.
- Giving the wrong number of elements when creating an array.
- Confusing `np.zeros()` with `np.ones()`.
- Using a Python list when a NumPy array is more suitable for numerical calculations.

## Advantages

- Provides several simple ways to create arrays.
- Saves time when creating large arrays.
- Useful for numerical calculations and data preparation.
- Makes it easy to create test data.

## Limitations

- The created array still needs to contain suitable data for the calculation being performed.
- Some array-creation functions may need extra attention when working with floating-point values or specific data types.

In [4]:
import numpy as np

# Creating a NumPy array from a Python list
sales = np.array([1200, 1500, 1800, 1600, 2000])

print("Sales array:")
print(sales)

# Creating an array containing five zeros
initial_values = np.zeros(5)

print("\nArray of zeros:")
print(initial_values)

# Creating an array containing five ones
basic_values = np.ones(5)

print("\nArray of ones:")
print(basic_values)

# Creating a sequence of numbers from 1 to 10
numbers = np.arange(1, 11)

print("\nNumbers from 1 to 10:")
print(numbers)

# Creating numbers with a gap of 2
even_numbers = np.arange(2, 11, 2)

print("\nEven numbers from 2 to 10:")
print(even_numbers)

Sales array:
[1200 1500 1800 1600 2000]

Array of zeros:
[0. 0. 0. 0. 0.]

Array of ones:
[1. 1. 1. 1. 1.]

Numbers from 1 to 10:
[ 1  2  3  4  5  6  7  8  9 10]

Even numbers from 2 to 10:
[ 2  4  6  8 10]


# 5. Dimensions

## Concept Explanation

The dimension of a NumPy array tells us how many levels of data the array has.

A simple list of values is a 1D array. Data arranged in rows and columns is a 2D array.

We can check the number of dimensions using `.ndim`.

## Real-world Example

A list of daily temperatures is a 1D array, while a table containing temperatures for different cities and days can be represented as a 2D array.

## Business Example

Monthly sales for several products can be stored in a 2D array, where rows represent products and columns represent months.

## AI/ML Example

In Machine Learning, a dataset containing multiple rows and features is commonly represented as a 2D array.

## Python Implementation

The example below creates 1D and 2D arrays and checks their dimensions.

## Output Explanation

The first array has one dimension, while the second array has two dimensions.

## Best Practice

Always check the dimensions of an array before performing operations that depend on its structure.

## Common Mistake

Do not confuse the number of dimensions with the total number of elements.

## Advantage

Knowing the dimensions helps us understand how the data is arranged.

## Limitation

Higher-dimensional arrays can become difficult to understand without checking their shape and structure.

In [5]:
import numpy as np

one_d = np.array([10, 20, 30])
two_d = np.array([[10, 20], [30, 40]])

print("1D dimensions:", one_d.ndim)
print("2D dimensions:", two_d.ndim)

1D dimensions: 1
2D dimensions: 2


# 6. Shape

## Concept Explanation

The shape of a NumPy array tells us how the data is arranged.

For a 1D array, the shape tells us the number of elements. For a 2D array, it tells us the number of rows and columns.

We can check the shape using the `.shape` attribute.

## Real-world Example

If we have the marks of 5 students, the shape can be `(5,)` because there are five values.

If we have marks for 3 students across 2 subjects, the shape can be `(3, 2)`.

## Business Example

A company may have sales data for 4 products across 3 months. The shape would be `(4, 3)`.

## AI/ML Example

In Machine Learning, the shape of a dataset helps us understand how many records and features are available.

For example, a dataset with 100 rows and 5 features has a shape of `(100, 5)`.

## Python Implementation

The code below creates a simple 2D array and checks its shape.

## Output Explanation

The output `(3, 2)` means the array contains 3 rows and 2 columns.

## Best Practice

Check the shape before performing operations that depend on the arrangement of the data.

## Common Mistake

Do not confuse `shape` with `size`. Shape describes the structure, while size gives the total number of elements.

In [6]:
import numpy as np

marks = np.array([
    [75, 80],
    [82, 78],
    [90, 88]
])

print("Shape:", marks.shape)

Shape: (3, 2)


# 7. Size

## Concept Explanation

The size of a NumPy array tells us the total number of elements present in the array.

We can find it using the `.size` attribute.

For example, an array with 3 rows and 2 columns contains 6 elements, so its size is 6.

## Real-world Example

If we have temperature readings for 7 days, the array contains 7 values, so its size is 7.

## Business Example

Suppose a company stores sales data for 4 products across 3 months. The array contains 4 × 3 = 12 values, so its size is 12.

## AI/ML Example

When working with a Machine Learning dataset, `.size` helps us know the total number of values stored in an array.

## Python Implementation

The code below checks the total number of elements in a 2D array.

## Output Explanation

The array has 3 rows and 2 columns, so it contains 6 elements in total.

## Best Practice

Use `.size` when you need the total number of elements rather than the number of rows or columns.

## Common Mistake

Do not confuse `.size` with `.shape`. Shape describes the structure, while size gives the total number of elements.

In [7]:
import numpy as np

data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print("Size:", data.size)

Size: 6


# 8. Data Types

## Concept Explanation

The data type tells us what kind of values are stored inside a NumPy array.

For example, an array can contain integers, decimal numbers, or Boolean values.

We can check the data type using the `.dtype` attribute.

## Real-world Example

Temperature values may contain decimal numbers such as `28.5`, while the number of customers may be stored as whole numbers such as `100`.

## Business Example

A company's product quantity can use integers, while product prices may use floating-point numbers.

## AI/ML Example

Machine Learning datasets often contain numerical features such as age, salary, or score. Knowing the data type helps us process these values correctly before using them in a model.

## Python Implementation

The code below creates arrays containing integers and decimal values and checks their data types.

## Output Explanation

The first array contains integers, while the second array contains floating-point values.

## Best Practice

Check the data type before performing calculations, especially when working with data from different sources.

## Common Mistake

Do not assume that every numerical array has the same data type.

## Advantages

Using appropriate data types can help with correct calculations and memory usage.

## Limitation

Choosing an unsuitable data type can cause unexpected results or loss of information.

In [8]:
import numpy as np

ages = np.array([22, 25, 30])
prices = np.array([99.5, 120.75, 150.0])

print("Age data type:", ages.dtype)
print("Price data type:", prices.dtype)

Age data type: int64
Price data type: float64


# 9. Indexing

## Concept Explanation

Indexing means accessing a particular value from a NumPy array.

Like Python lists, NumPy uses zero-based indexing. This means the first element has index `0`, the second has index `1`, and so on.

For a 2D array, we can use both the row and column index to access a specific value.

## Real-world Example

If we have the daily temperatures of a week, indexing can be used to access the temperature recorded on a particular day.

## Business Example

A company may store sales data in an array. Indexing can be used to access the sales value of a particular product or month.

## AI/ML Example

In Machine Learning, indexing is useful when selecting a particular feature, row, or value from a dataset during data preprocessing.

## Python Implementation

The code below shows indexing in both a 1D and a 2D array.

## Output Explanation

The first example accesses the second value from the 1D array.

The 2D example accesses the value at the first row and second column.

## Best Practice

Remember that NumPy indexing starts from `0`.

## Common Mistake

Using `1` to access the first element instead of `0`.

In [9]:
import numpy as np

marks = np.array([75, 82, 90, 68])

print("Second mark:", marks[1])

sales = np.array([
    [1000, 1200],
    [1500, 1800]
])

print("First row, second value:", sales[0, 1])

Second mark: 82
First row, second value: 1200


# 10. Slicing

## Concept Explanation

Slicing is used to select a part of a NumPy array instead of accessing only one value.

The basic syntax is:

`array[start:stop]`

The start index is included, but the stop index is not included.

## Real-world Example

If we have temperature readings for seven days, slicing can be used to select the readings for only a few days.

## Business Example

A company may have monthly sales stored in an array. Slicing can be used to select sales for a particular group of months.

## AI/ML Example

In Machine Learning, slicing can be useful for selecting a group of rows or features from an array during data preprocessing.

## Python Implementation

The example below selects a few values from a NumPy array using slicing.

## Output Explanation

The selected values are returned based on the starting and stopping indexes.

## Best Practice

Remember that the stop index is not included in the result.

## Common Mistake

A common mistake is expecting the value at the stop index to be included.

In [10]:
import numpy as np

sales = np.array([100, 150, 200, 250, 300])

# Select values from index 1 to 3
selected = sales[1:4]

print("Selected values:", selected)

Selected values: [150 200 250]


# 11. Reshaping

## Concept Explanation

Reshaping means changing the structure of a NumPy array without changing the actual values.

For example, a 1D array containing 6 values can be changed into a 2D array with 2 rows and 3 columns.

The total number of elements must remain the same before and after reshaping.

## Real-world Example

Suppose we have six sales values collected over six months. We can arrange them into a 2 × 3 structure if we want to organize the values into rows and columns.

## Business Example

A company may receive data as a single list but need to arrange it into rows and columns for further analysis.

## AI/ML Example

Reshaping is commonly used in Machine Learning when the input data needs to be in a particular shape expected by an algorithm or model.

## Python Implementation

The code below changes a 1D array containing six values into a 2D array with 2 rows and 3 columns.

## Output Explanation

The values remain the same, but their arrangement changes from one dimension to two dimensions.

## Best Practice

Before reshaping, make sure the new shape can contain the same total number of elements.

## Common Mistake

Trying to reshape an array into a shape that does not have the same total number of elements.

In [11]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60])

reshaped = data.reshape(2, 3)

print("Original:", data)
print("Reshaped:\n", reshaped)

Original: [10 20 30 40 50 60]
Reshaped:
 [[10 20 30]
 [40 50 60]]


# 12. Flatten

## Concept Explanation

Flattening means converting a multi-dimensional NumPy array into a single 1D array.

For example, a 2D array with rows and columns can be converted into one continuous list of values.

NumPy provides the `.flatten()` method for this.

## Real-world Example

Suppose sales data is stored in rows and columns for different products and months. Flattening can convert the complete data into one sequence of values when a single-dimensional structure is needed.

## Business Example

A company may want to process all values from a small table as one sequence for a particular calculation or analysis.

## AI/ML Example

Some Machine Learning tasks require data to be represented as a single-dimensional array. Flattening can be used to convert structured numerical data into a 1D form before further processing.

## Python Implementation

The code below converts a 2D array into a 1D array using `flatten()`.

## Output Explanation

The original data has rows and columns, while the flattened result contains all the values in a single dimension.

## Best Practice

Use `flatten()` when an independent 1D copy of the array is needed.

## Common Mistake

Do not confuse flattening with reshaping. Flattening specifically converts the array into one dimension.

In [12]:
import numpy as np

data = np.array([[10, 20, 30], [40, 50, 60]])

flattened = data.flatten()

print("Original:\n", data)
print("Flattened:", flattened)

Original:
 [[10 20 30]
 [40 50 60]]
Flattened: [10 20 30 40 50 60]


# 13. Copy vs View

## Concept Explanation

In NumPy, a copy and a view may look similar, but they work differently.

A **copy** creates a separate array. If we change the copy, the original array is not affected.

A **view** shares the same underlying data with the original array. So, changing the view can also change the original array.

## Real-world Example

Think of a copy like making a photocopy of a document. You can change the photocopy without changing the original.

A view is more like looking at the same document from another place. Changes to the shared document can be seen from both places.

## Business Example

When working with a large business dataset, creating unnecessary copies can use more memory. A view can sometimes be useful when we only need another way to access the same data.

## AI/ML Example

In AI/ML data preprocessing, understanding copy and view is important when modifying arrays. Accidentally changing the original data can affect later steps in the workflow.

## Python Implementation

The example below shows the difference between a copy and a view.

## Output Explanation

Changing the copy does not change the original array. However, changing the view also changes the original array because they share the same data.

## Best Practice

Use `.copy()` when you need an independent array that can be changed safely.

## Common Mistake

Assuming that every new array variable contains completely separate data.

## Advantage

Views can avoid unnecessary copying and can save memory.

## Limitation

Views can cause unexpected changes to the original data if we are not careful.

In [13]:
import numpy as np

original = np.array([10, 20, 30])

# Copy
copied = original.copy()
copied[0] = 100

# View
view = original.view()
view[1] = 200

print("Original:", original)
print("Copy:", copied)
print("View:", view)

Original: [ 10 200  30]
Copy: [100  20  30]
View: [ 10 200  30]


# 14. Broadcasting

## Concept Explanation

Broadcasting is a NumPy feature that allows us to perform operations on arrays with compatible shapes.

The simple idea is that NumPy can automatically apply a smaller value or array to a larger array during a calculation.

For example, if we add `10` to an array, NumPy adds `10` to every element without us writing a loop.

## Real-world Example

Suppose we have prices of several products and want to increase every price by ₹10. Broadcasting allows us to add 10 to all prices at once.

## Business Example

A company can use broadcasting to apply the same discount, tax, or price adjustment to many products at the same time.

## AI/ML Example

Broadcasting is useful in Machine Learning when applying the same value or operation across multiple features or data points during preprocessing.

## Python Implementation

The example below adds the same value to every element in a NumPy array.

## Output Explanation

NumPy automatically applies `10` to every value in the array.

## Best Practice

Before using broadcasting with multiple arrays, check whether their shapes are compatible.

## Common Mistake

Trying to perform operations on arrays with shapes that cannot be broadcast together.

## Advantage

Broadcasting makes array calculations shorter and avoids unnecessary loops.

## Limitation

Broadcasting can sometimes be confusing when the array shapes are different.

In [14]:
import numpy as np

prices = np.array([100, 200, 300, 400])

updated_prices = prices + 10

print("Original prices:", prices)
print("Updated prices:", updated_prices)

Original prices: [100 200 300 400]
Updated prices: [110 210 310 410]


# 15. Array Operations

## Concept Explanation

NumPy allows us to perform common mathematical operations directly on arrays.

We can perform addition, subtraction, multiplication, division, and other calculations without writing a separate loop for each element.

When two arrays have the same shape, the operation is normally performed element by element.

## Real-world Example

Suppose we have the number of products sold in two different weeks. We can add the arrays to find the total products sold across both weeks.

## Business Example

A company can compare sales, costs, or quantities from different periods using NumPy array operations.

## AI/ML Example

Array operations are commonly used in Machine Learning for calculations involving features, values, and numerical data during preprocessing and model development.

## Python Implementation

The example below performs basic mathematical operations on two NumPy arrays.

## Output Explanation

Each operation is performed element by element between the two arrays.

## Best Practice

Make sure the arrays have compatible shapes before performing operations.

## Common Mistake

Assuming `*` performs matrix multiplication. In NumPy, `*` performs element-wise multiplication.

## Advantages

- Simple and readable numerical calculations.
- Avoids unnecessary loops.
- Works efficiently with arrays.

## Limitations

- Arrays need compatible shapes for many operations.
- Different operations have different rules, especially when working with multi-dimensional arrays.

In [15]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


# 16. Universal Functions (ufuncs)

## Concept Explanation

Universal functions, commonly called `ufuncs`, are NumPy functions that perform an operation on each element of an array.

They are useful for mathematical calculations because we can apply a function to the complete array without writing a loop.

Some common examples are:

- `np.sqrt()` – square root
- `np.square()` – square of each value
- `np.exp()` – exponential
- `np.log()` – logarithm

## Real-world Example

Suppose we have the distances travelled by different vehicles. We can use NumPy functions to perform mathematical calculations on all the values at once.

## Business Example

A business may use mathematical functions while analysing sales, revenue, growth, or other numerical data.

## AI/ML Example

ufuncs are useful in AI/ML preprocessing and numerical calculations where the same mathematical operation needs to be applied to many values.

## Python Implementation

The example below uses `np.sqrt()` and `np.square()` on a NumPy array.

## Output Explanation

The functions are applied to each value in the array and return the calculated result for every element.

## Best Practice

Use NumPy's built-in functions when they provide the operation you need instead of writing unnecessary loops.

## Common Mistake

Using a Python function that works with a single value when a NumPy function can process the complete array.

## Advantages

- Simple to use.
- Works directly with NumPy arrays.
- Avoids unnecessary loops.
- Useful for many mathematical operations.

## Limitations

- Some functions may produce warnings or unexpected values for unsuitable input data.
- You need to understand the mathematical operation before applying it.

In [16]:
import numpy as np

values = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(values))
print("Square:", np.square(values))

Square root: [1. 2. 3. 4.]
Square: [  1  16  81 256]


# Interview Questions

### 1. What is NumPy?

NumPy is a Python library used mainly for numerical computing. Its main data structure is the N-dimensional array called `ndarray`.

### 2. What is the difference between a Python list and a NumPy array?

A Python list is a general-purpose collection, while a NumPy array is designed mainly for numerical operations and supports efficient array-based calculations.

### 3. What is broadcasting in NumPy?

Broadcasting allows NumPy to perform operations between arrays with compatible shapes without manually changing their dimensions.

### 4. What is the difference between a copy and a view?

A copy creates independent data, so changes to the copy do not affect the original array. A view can share the same underlying data, so changes to the view may also affect the original array.

### 5. What is the difference between `shape`, `size`, and `ndim`?

`shape` tells us the structure of the array, `size` gives the total number of elements, and `ndim` tells us the number of dimensions.

### 6. What is a ufunc?

A ufunc, or Universal Function, is a NumPy function that performs an operation element by element on an array, such as `np.sqrt()` or `np.square()`.

### 7. Why is NumPy useful in Machine Learning?

NumPy makes it easier to store and process numerical data. Many Machine Learning operations involve arrays and mathematical calculations, so NumPy provides a useful foundation for data preprocessing and numerical computation.

---

# Self Reflection

In this notebook, I learned the basic concepts of NumPy and how NumPy arrays are different from normal Python lists.

I practiced creating arrays, checking their dimensions and shape, accessing and slicing values, reshaping arrays, and performing mathematical operations.

I also understood concepts such as copy and view, broadcasting, and universal functions.

These concepts give me a good foundation for working with numerical data and will be useful when I move further into Pandas, Data Analysis, and Machine Learning.