# _NumPy_Math_

# 1. Sum

## Concept Explanation

Sum means adding all the values in an array.

NumPy provides the `np.sum()` function to calculate the total of the values quickly.

## Real-world Example

Suppose we have the number of products sold over five days. We can use sum to find the total number of products sold during those days.

## Business Example

A company can use the sum function to calculate total sales, total expenses, or total units sold.

## AI/ML Example

In AI/ML, sum operations are commonly used during numerical calculations and data preprocessing.

## Python Implementation

The code below calculates the total of the values in a NumPy array.

## Output Explanation

The output gives the total value of all the elements in the array.

## Best Practice

Use `np.sum()` when you need the total of numerical values in an array.

## Common Mistake

Do not confuse the total sum with the average of the values.

In [1]:
import numpy as np

sales = np.array([100, 150, 200, 250])

total = np.sum(sales)

print("Total sales:", total)

Total sales: 700


# 2. Mean

## Concept Explanation

Mean is the average value of a group of numbers.

To find the mean, we add all the values and divide the total by the number of values.

NumPy provides the `np.mean()` function to calculate it easily.

## Real-world Example

If the temperatures for five days are 28, 30, 29, 31, and 32, the mean gives us the average temperature for those days.

## Business Example

A company can use mean to find the average monthly sales, average customer spending, or average number of products sold.

## AI/ML Example

Mean is commonly used in data preprocessing and statistics. For example, it can be used to understand the average value of a feature and is also useful in techniques such as mean-based missing value handling.

## Python Implementation

The code below calculates the average of a set of values.

## Output Explanation

The output shows the average value of all the elements in the array.

## Best Practice

Use the mean when the data does not have extreme values that could strongly affect the average.

## Common Mistake

The mean can be affected by very high or very low values, so it should not always be used as the only measure of the center of the data.

In [2]:
import numpy as np

marks = np.array([70, 80, 75, 90, 85])

average = np.mean(marks)

print("Mean:", average)

Mean: 80.0


# 3. Median

## Concept Explanation

Median is the middle value of a set of numbers after the values are arranged in order.

If there is an even number of values, the median is the average of the two middle values.

NumPy provides the `np.median()` function to calculate it.

## Real-world Example

Suppose the ages of five people are 22, 25, 28, 30, and 35. The median age is 28 because it is the middle value.

## Business Example

A company can use the median to understand typical customer spending when a few customers have unusually high or low spending.

## AI/ML Example

Median is useful in Machine Learning for understanding data and handling outliers. It is also commonly used for filling missing numerical values when the data contains extreme values.

## Python Implementation

The code below calculates the median of a NumPy array.

## Output Explanation

The output shows the middle value after the data is considered in sorted order.

## Best Practice

Median is often a good choice when the data contains extreme values because it is less affected by them.

## Common Mistake

Do not assume the median is always the same as the mean.

In [3]:
import numpy as np

ages = np.array([22, 25, 28, 30, 35])

median_age = np.median(ages)

print("Median:", median_age)

Median: 28.0


# 4. Variance

## Concept Explanation

Variance tells us how much the values in a dataset differ from their mean.

A small variance means the values are close to the average. A large variance means the values are more spread out.

NumPy provides the `np.var()` function to calculate variance.

## Real-world Example

If the daily temperatures are very close to each other, the variance will be small. If the temperatures change a lot from day to day, the variance will be larger.

## Business Example

A company can use variance to understand how much sales values change from one period to another.

## AI/ML Example

Variance helps us understand how much a feature varies in a dataset. It is also useful when analysing features during Machine Learning preprocessing.

## Python Implementation

The code below calculates the variance of a small dataset.

## Output Explanation

The output represents the average squared difference of the values from their mean.

## Best Practice

Use variance when you need to understand how spread out numerical data is.

## Common Mistake

Variance is measured in squared units, so it is not always as easy to interpret as standard deviation.

In [4]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

variance = np.var(data)

print("Variance:", variance)

Variance: 200.0


# 5. Standard Deviation

## Concept Explanation

Standard deviation tells us how much the values in a dataset normally vary from the mean.

A small standard deviation means the values are close to the average. A large standard deviation means the values are more spread out.

Standard deviation is easier to interpret than variance because it is in the same units as the original data.

NumPy provides the `np.std()` function to calculate it.

## Real-world Example

If the daily temperatures are close to the average temperature, the standard deviation will be small. If the temperatures change significantly, it will be larger.

## Business Example

A company can use standard deviation to understand how much sales vary over different months.

## AI/ML Example

Standard deviation is commonly used to understand the spread of Machine Learning features and is also important in data preprocessing and standardization.

## Python Implementation

The code below calculates the standard deviation of a small dataset.

## Output Explanation

The output shows how much the values typically vary around their mean.

## Best Practice

Use standard deviation when you want an easy-to-understand measure of data spread.

## Common Mistake

Do not confuse standard deviation with variance. Standard deviation is the square root of variance.

In [5]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

std = np.std(data)

print("Standard Deviation:", std)

Standard Deviation: 14.142135623730951


# 6. Minimum

## Concept Explanation

Minimum means finding the smallest value in a dataset.

NumPy provides the `np.min()` function to find the smallest value in an array.

## Real-world Example

If we have the temperatures recorded during a week, the minimum gives us the lowest temperature recorded.

## Business Example

A company can use the minimum function to find the lowest sales, lowest price, or minimum number of products sold during a period.

## AI/ML Example

In AI/ML, minimum values can be useful when understanding the range of a feature during data analysis and preprocessing.

## Python Implementation

The code below finds the smallest value in a NumPy array.

## Output Explanation

The output shows the lowest value present in the array.

## Best Practice

Use `np.min()` when you need the smallest numerical value.

## Common Mistake

Do not confuse the minimum value with its position or index in the array.

In [6]:
import numpy as np

temperatures = np.array([28, 31, 25, 30, 27])

minimum = np.min(temperatures)

print("Minimum temperature:", minimum)

Minimum temperature: 25


# 7. Maximum

## Concept Explanation

Maximum means finding the largest value in a dataset.

NumPy provides the `np.max()` function to find the largest value in an array.

## Real-world Example

If we have the temperatures recorded during a week, the maximum gives us the highest temperature recorded.

## Business Example

A company can use the maximum function to find the highest sales, highest revenue, or maximum number of products sold during a period.

## AI/ML Example

In AI/ML, maximum values can help us understand the range of a feature during data analysis and preprocessing.

## Python Implementation

The code below finds the largest value in a NumPy array.

## Output Explanation

The output shows the highest value present in the array.

## Best Practice

Use `np.max()` when you need the largest numerical value.

## Common Mistake

Do not confuse the maximum value with the position or index where it occurs.

In [7]:
import numpy as np

temperatures = np.array([28, 31, 25, 30, 27])

maximum = np.max(temperatures)

print("Maximum temperature:", maximum)

Maximum temperature: 31


# 8. Argmin

## Concept Explanation

`argmin` gives us the index or position of the smallest value in an array.

NumPy provides the `np.argmin()` function for this.

The important difference is that `np.min()` returns the smallest value, while `np.argmin()` returns its position.

## Real-world Example

If we have daily temperatures, `argmin` can tell us the position of the day with the lowest temperature.

## Business Example

A company can use `argmin` to find which month or product has the lowest sales value.

## AI/ML Example

In AI/ML, `argmin` can be useful when we need to find the position of the smallest value, such as selecting the feature or result with the lowest calculated value.

## Python Implementation

The code below finds the position of the smallest value.

## Output Explanation

The output is the index where the minimum value is located.

## Best Practice

Use `argmin` when you need the position of the minimum value rather than the value itself.

## Common Mistake

Do not expect `np.argmin()` to return the minimum value. Use `np.min()` for that.

In [8]:
import numpy as np

sales = np.array([500, 300, 450, 600, 400])

print("Maximum value:", np.max(sales))
print("Index of maximum:", np.argmax(sales))

Maximum value: 600
Index of maximum: 3


# 10. Percentile

## Concept Explanation

A percentile tells us the value below which a certain percentage of the data falls.

For example, the 50th percentile represents the middle of the data and is related to the median.

NumPy provides the `np.percentile()` function to calculate percentiles.

## Real-world Example

If a student's score is at the 90th percentile, it means the score is higher than or equal to the scores of most students in the group.

## Business Example

A company can use percentiles to understand customer spending. For example, the 90th percentile can show a spending level that only a small percentage of customers exceed.

## AI/ML Example

Percentiles can be useful in data analysis and preprocessing to understand the distribution of features and identify unusually high or low values.

## Python Implementation

The code below calculates the 50th and 90th percentiles of a dataset.

## Output Explanation

The output shows the values below which approximately 50% and 90% of the data fall.

## Best Practice

Use percentiles when you want to understand the position of a value within a dataset.

## Common Mistake

Do not confuse a percentile with a percentage. A percentile describes the position of a value within a dataset.

In [9]:
import numpy as np

scores = np.array([50, 60, 70, 80, 90, 100])

print("50th percentile:", np.percentile(scores, 50))
print("90th percentile:", np.percentile(scores, 90))

50th percentile: 75.0
90th percentile: 95.0


# 11. Dot Product

## Concept Explanation

The dot product combines corresponding values from two arrays, multiplies them, and then adds the results together.

For example, for `[1, 2, 3]` and `[4, 5, 6]`:

`(1 × 4) + (2 × 5) + (3 × 6) = 32`

NumPy provides `np.dot()` to calculate the dot product.

## Real-world Example

Suppose we have the quantity of three products and their prices. The dot product can help calculate the total value of all the products.

## Business Example

A company can use the dot product to calculate total revenue when it has product quantities and prices.

## AI/ML Example

Dot products are an important part of Machine Learning calculations. They are used in operations involving features and model weights, such as linear models and neural networks.

## Python Implementation

The code below calculates the dot product of two simple arrays.

## Output Explanation

The output is the sum of the products of the corresponding values.

## Best Practice

Make sure the arrays have compatible dimensions before calculating the dot product.

## Common Mistake

Do not confuse the dot product with simple element-wise multiplication.

In [10]:
import numpy as np

quantities = np.array([2, 3, 4])
prices = np.array([100, 200, 150])

total = np.dot(quantities, prices)

print("Total value:", total)

Total value: 1400


# 12. Matrix Multiplication

## Concept Explanation

Matrix multiplication is an operation where two matrices are multiplied together following specific row and column rules.

In NumPy, we can use `np.matmul()` or the `@` operator for matrix multiplication.

For multiplication to be possible, the number of columns in the first matrix must match the number of rows in the second matrix.

## Real-world Example

Matrix multiplication can be used when combining different sets of numerical information, such as quantities and related values.

## Business Example

A company can use matrix multiplication to combine sales data with product weights, prices, or other numerical factors.

## AI/ML Example

Matrix multiplication is very important in Machine Learning. It is used in calculations involving feature matrices and model weights and is a core operation inside neural networks.

## Python Implementation

The example below multiplies two small matrices using NumPy.

## Output Explanation

The resulting matrix is calculated by multiplying the rows of the first matrix with the columns of the second matrix.

## Best Practice

Check the dimensions of both matrices before performing matrix multiplication.

## Common Mistake

Do not confuse matrix multiplication with element-wise multiplication using `*`.

In [11]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A @ B

print("Result:")
print(result)

Result:
[[19 22]
 [43 50]]


# 13. Transpose

## Concept Explanation

Transpose means changing the rows of a matrix into columns and the columns into rows.

In NumPy, we can use `.T` to find the transpose of an array.

For example, a matrix with 2 rows and 3 columns becomes a matrix with 3 rows and 2 columns after transposing.

## Real-world Example

Suppose information is arranged with students as rows and subjects as columns. Transposing the data can change the arrangement so that subjects become rows.

## Business Example

A company may have sales data arranged by products and months. Transposing can change the structure so that months become rows and products become columns.

## AI/ML Example

Transpose operations are commonly used in Machine Learning and numerical computing when changing the orientation of matrices for calculations.

## Python Implementation

The code below finds the transpose of a simple matrix.

## Output Explanation

The rows of the original matrix become columns in the transposed matrix.

## Best Practice

Check the shape of the matrix before and after transposing when the structure matters.

## Common Mistake

Do not assume that transposing changes the actual values. It changes their arrangement.

In [12]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original:\n", matrix)
print("Transpose:\n", matrix.T)

Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


# 14. Basic Linear Algebra Operations

## Concept Explanation

Linear algebra is an important part of numerical computing and Machine Learning.

NumPy provides several functions for working with vectors and matrices, such as dot products, matrix multiplication, transpose, and other matrix operations.

These operations help us work with numerical data in a structured way.

## Real-world Example

Linear algebra can be used to represent and calculate relationships between different sets of numerical information.

For example, a system can represent measurements, quantities, or other numerical values as vectors and matrices.

## Business Example

A business can use matrix-based calculations to work with sales, costs, customer information, and other numerical data.

## AI/ML Example

Linear algebra is one of the basic mathematical foundations of Machine Learning.

Operations such as matrix multiplication and dot products are used when calculating predictions, transforming features, and processing data inside Machine Learning models.

## Python Implementation

The example below demonstrates a few basic linear algebra operations using NumPy.

## Output Explanation

The output shows the result of a dot product, matrix multiplication, and transpose operation.

## Best Practice

Keep track of the dimensions of vectors and matrices before performing linear algebra operations.

## Common Mistake

Using incompatible matrix dimensions for multiplication can result in an error.

In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Dot product:", np.dot(a, b))
print("Matrix multiplication:\n", A @ B)
print("Transpose:\n", A.T)

Dot product: 32
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


# Interview Questions

### 1. What is the difference between `np.mean()` and `np.median()`?

`np.mean()` calculates the average of the values, while `np.median()` returns the middle value after the data is arranged in order.

### 2. What is the difference between variance and standard deviation?

Variance measures the spread of data using squared differences from the mean. Standard deviation is the square root of variance and is easier to interpret because it uses the same units as the original data.

### 3. What is the difference between `np.min()` and `np.argmin()`?

`np.min()` returns the smallest value, while `np.argmin()` returns the index where the smallest value is located.

### 4. What is the difference between `np.max()` and `np.argmax()`?

`np.max()` returns the largest value, while `np.argmax()` returns the index where the largest value is located.

### 5. What is a dot product?

A dot product multiplies corresponding values from two arrays and adds the results together. It is commonly used in numerical computing and Machine Learning.

### 6. What is the difference between element-wise multiplication and matrix multiplication?

Element-wise multiplication multiplies corresponding elements using `*`. Matrix multiplication follows the row-column multiplication rule and can be performed using `@` or `np.matmul()`.

### 7. What does transpose do?

Transpose changes the rows of a matrix into columns and the columns into rows.

### 8. Why is linear algebra important in Machine Learning?

Linear algebra provides the mathematical operations needed to work with vectors and matrices. Operations such as dot products and matrix multiplication are used in many Machine Learning algorithms and neural networks.

---

# Self Reflection

In this notebook, I learned how NumPy can be used for different mathematical and statistical calculations.

I practiced finding the mean, median, variance, standard deviation, minimum, maximum, and percentiles.

I also learned how to find the position of minimum and maximum values using `argmin` and `argmax`.

The concepts of dot product, matrix multiplication, transpose, and basic linear algebra helped me understand how NumPy is connected to Machine Learning.

Overall, this notebook gave me a better understanding of how numerical operations are performed using NumPy.