# Notebook - 15_Mini_Assessment_

# Question 1 – Create a NumPy Array

Create a NumPy array containing the following numbers:

10, 20, 30, 40, 50

Print the array.

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


# Question 2 – NumPy Array vs Python List

## Answer

A Python List can store different types of data and is a general-purpose collection.

A NumPy Array is designed mainly for numerical data and supports fast mathematical and vectorized operations.

### Key Difference

- Python List: General-purpose and can contain different data types.
- NumPy Array: Mainly used for numerical data and provides efficient mathematical operations.

### Advantage of NumPy Array

NumPy Arrays are generally faster and more memory-efficient for numerical operations compared with Python Lists.

In [3]:
import numpy as np

list_data = [10, 20, 30]
array_data = np.array([10, 20, 30])

print(list_data)
print(array_data)

[10, 20, 30]
[10 20 30]


# Question 3 – NumPy Broadcasting

## Question

Explain NumPy Broadcasting with an example.

Create a NumPy array containing:

10, 20, 30

Add 5 to the array using broadcasting and display the result.

In [4]:
import numpy as np

arr = np.array([10, 20, 30])

result = arr + 5

print(result)

[15 25 35]


# Question 4 – Series vs DataFrame

## Question

Explain the difference between a Pandas Series and a Pandas DataFrame.

## Answer

### Pandas Series

A Series is a one-dimensional labeled data structure in Pandas. It contains a single column of data along with an index.

### Pandas DataFrame

A DataFrame is a two-dimensional labeled data structure in Pandas. It contains data arranged in rows and columns.

### Difference Between Series and DataFrame

| Series | DataFrame |
|--------|-----------|
| One-dimensional | Two-dimensional |
| Contains a single column of data | Contains multiple rows and columns |
| Similar to a single column | Similar to a table |
| Has one axis of labels | Has row and column labels |

## Example

Create one Pandas Series and one Pandas DataFrame and display them.

In [6]:
import pandas as pd

series = pd.Series([80, 85, 90])

df = pd.DataFrame({
    "Name": ["Akash", "Rahul", "Ananya"],
    "Marks": [80, 85, 90]
})

print("Series:")
print(series)

print("\nDataFrame:")
print(df)

Series:
0    80
1    85
2    90
dtype: int64

DataFrame:
     Name  Marks
0   Akash     80
1   Rahul     85
2  Ananya     90


# Question 5 – Read a CSV File Using Pandas

## Question

How do you read a CSV file using Pandas?

## Answer

A CSV (Comma-Separated Values) file stores data in rows and columns.

Pandas provides the `read_csv()` function to read a CSV file and load its data into a DataFrame.

## Example

Read a CSV file named `students.csv` using Pandas and display the data.

In [7]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

      Name  Marks
0  Akash R     85
1    Rahul     78


# Question 6 – Merge Two DataFrames

## Question

What is `merge()` in Pandas?

Merge two DataFrames using a common column.

## Answer

The `merge()` function is used to combine two Pandas DataFrames based on a common column or key.

It is similar to joining tables in SQL.

## Example

Create two DataFrames with a common `ID` column and merge them using the `ID` column.

In [8]:
import pandas as pd

df1 = pd.DataFrame({
    "ID": [1, 2],
    "Name": ["Akash", "Rahul"]
})

df2 = pd.DataFrame({
    "ID": [1, 2],
    "Marks": [85, 78]
})

result = pd.merge(df1, df2, on="ID")

print(result)

   ID   Name  Marks
0   1  Akash     85
1   2  Rahul     78


# Question 7 – GroupBy and Aggregation

## Question

What is `groupby()` in Pandas?

Perform GroupBy and Aggregation on a DataFrame to calculate the average marks for each city.

## Answer

The `groupby()` function is used to divide data into groups based on one or more columns.

Aggregation functions such as `mean()`, `sum()`, `count()`, `min()`, and `max()` can then be applied to each group.

## Example

Create a DataFrame containing student names, cities, and marks. Group the data by city and calculate the average marks.

In [9]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Bangalore", "Chennai", "Bangalore", "Chennai"],
    "Marks": [80, 90, 90, 70]
})

result = df.groupby("City")["Marks"].mean()

print(result)

City
Bangalore    85.0
Chennai      80.0
Name: Marks, dtype: float64


# Question 8 – Filter Rows Based on Multiple Conditions

## Question

How do you filter rows in a Pandas DataFrame using multiple conditions?

Filter the students who are from Bangalore and have marks greater than 80.

## Answer

Boolean indexing is used to filter rows based on conditions.

Multiple conditions can be combined using operators such as:

- `&` for AND
- `|` for OR
- `~` for NOT

Each condition should be placed inside parentheses.

## Example

Create a DataFrame and filter students who are from Bangalore and have marks greater than 80.

In [10]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Akash", "Rahul", "Ananya"],
    "City": ["Bangalore", "Chennai", "Bangalore"],
    "Marks": [85, 90, 75]
})

result = df[(df["City"] == "Bangalore") & (df["Marks"] > 80)]

print(result)

    Name       City  Marks
0  Akash  Bangalore     85


# Question 9 – Handle Missing Values

## Question

How do you identify and handle missing values in a Pandas DataFrame?

Create a DataFrame with a missing value and replace the missing value using `fillna()`.

## Answer

Missing values are values that are not available in a dataset.

Pandas provides methods such as:

- `isnull()` to identify missing values.
- `notnull()` to identify available values.
- `dropna()` to remove missing values.
- `fillna()` to replace missing values.

## Example

Create a DataFrame with a missing marks value and replace it with `80`.

In [11]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Akash", "Rahul"],
    "Marks": [85, None]
})

df["Marks"] = df["Marks"].fillna(80)

print(df)

    Name  Marks
0  Akash   85.0
1  Rahul   80.0


# Question 10 – Statistical Measures Using NumPy

## Question

How can you calculate statistical measures using NumPy?

Create a NumPy array containing the values 10, 20, 30, 40, and 50.

Calculate and display the:

- Mean
- Median
- Minimum
- Maximum

In [12]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))

Mean: 30.0
Median: 30.0
Minimum: 10
Maximum: 50


# Question 11 – Optimize a DataFrame for Memory Usage

## Question

How can you optimize a Pandas DataFrame for memory usage?

Create a DataFrame containing repeated city names and convert the `City` column to the `category` data type.

## Answer

Memory optimization means reducing the amount of memory used by a DataFrame while keeping the required data.

One common technique is converting suitable columns with repeated categorical values to the `category` data type.

## Example

Create a DataFrame with city names and convert the `City` column to the `category` data type.

In [13]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Bangalore", "Chennai", "Bangalore", "Chennai"]
})

df["City"] = df["City"].astype("category")

print(df.dtypes)

City    category
dtype: object
